version: '3'

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"  # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./config/dynamic_conf.yml:/etc/traefik/dynamic_conf/conf.yml:ro
      - ./config/acme.json:/etc/traefik/acme.json
    networks:
      - traefik_network

  # Contoh service whoami untuk pengujian
  whoami:
    image: traefik/whoami
    container_name: whoami
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls=true"
      - "traefik.http.middlewares.whoami-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.whoami.middlewares=whoami-headers"
      - "traefik.http.services.whoami.loadbalancer.server.port=80"
    networks:
      - traefik_network

networks:
  traefik_network:
    driver: bridge