// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");
var Json_encode = require("@glennsl/bs-json/src/Json_encode.bs.js");

function read_t(json) {
  return /* record */[
          /* id */Json_decode.field("id", Json_decode.string, json),
          /* title */Json_decode.field("item", Json_decode.string, json),
          /* checked */Json_decode.field("checked", Json_decode.bool, json)
        ];
}

function read_response(param) {
  return Json_decode.list(read_t, param);
}

function read_todo_t(json) {
  return /* record */[
          /* id */Json_decode.field("id", Json_decode.string, json),
          /* title */Json_decode.field("item", Json_decode.string, json),
          /* checked */Json_decode.field("checked", Json_decode.bool, json)
        ];
}

function write_t(t) {
  return Json_encode.object_(/* :: */[
              /* tuple */[
                "id",
                t[/* id */0]
              ],
              /* :: */[
                /* tuple */[
                  "item",
                  t[/* title */1]
                ],
                /* :: */[
                  /* tuple */[
                    "checked",
                    t[/* checked */2]
                  ],
                  /* [] */0
                ]
              ]
            ]);
}

exports.read_t = read_t;
exports.read_response = read_response;
exports.read_todo_t = read_todo_t;
exports.write_t = write_t;
/* No side effect */
