// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");
var React = require("react");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("Todo_AddInput");

var input = Css.style(/* :: */[
      Css.borderColor(/* `hex */[
            5194459,
            "#DCDEDD"
          ]),
      /* :: */[
        Css.padding(/* `rem */[
              5691738,
              0.4
            ]),
        /* :: */[
          Css.focus(/* :: */[
                Css.outlineWidth(/* zero */-789508312),
                /* :: */[
                  Css.borderColor(/* `hex */[
                        5194459,
                        "000000"
                      ]),
                  /* [] */0
                ]
              ]),
          /* [] */0
        ]
      ]
    ]);

var Styles = /* module */[/* input */input];

function make(value, onChange, onKeyDown, disabled, _children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              var tmp = {
                className: input,
                type: "text",
                value: value,
                onKeyDown: onKeyDown,
                onChange: onChange
              };
              if (disabled !== undefined) {
                tmp.disabled = Caml_option.valFromOption(disabled);
              }
              return React.createElement("input", tmp);
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.Styles = Styles;
exports.make = make;
/* component Not a pure module */
